/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CollaborationInvitation {
  'id' : InvitationId,
  'status' : InvitationStatus,
  'expiresAt' : Timestamp,
  'createdAt' : Timestamp,
  'role' : CollaboratorRole,
  'inviteeId' : UserId,
  'inviterId' : UserId,
  'videoId' : VideoId,
}
export interface Collaborator {
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'role' : CollaboratorRole,
  'videoId' : VideoId,
}
export type CollaboratorRole = { 'editor' : null } |
  { 'viewer' : null };
export interface Collection {
  'id' : CollectionId,
  'title' : string,
  'ownerId' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'visibility' : CollectionVisibility,
  'videoIds' : Array<VideoId>,
}
export type CollectionId = bigint;
export type CollectionVisibility = { 'public' : null } |
  { 'private' : null };
export interface Comment {
  'id' : CommentId,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
  'timestampSeconds' : bigint,
  'videoId' : VideoId,
}
export type CommentId = bigint;
export interface CreateCollectionInput {
  'title' : string,
  'description' : string,
  'visibility' : CollectionVisibility,
}
export interface CreateCommentInput {
  'text' : string,
  'timestampSeconds' : bigint,
  'videoId' : VideoId,
}
export interface CreateVideoInput {
  'title' : string,
  'description' : string,
  'videoBlob' : ExternalBlob,
  'thumbnailBlob' : [] | [ExternalBlob],
  'durationSeconds' : bigint,
  'visibility' : VideoVisibility,
}
export type ExternalBlob = Uint8Array;
export type InvitationId = bigint;
export type InvitationStatus = { 'revoked' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface SaveProfileInput {
  'bio' : string,
  'displayName' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type Timestamp = bigint;
export interface UpdateCollectionInput {
  'title' : string,
  'description' : string,
  'visibility' : CollectionVisibility,
}
export interface UpdateVideoInput {
  'title' : string,
  'description' : string,
  'visibility' : VideoVisibility,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'displayName' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'status' : VideoStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'videoBlob' : ExternalBlob,
  'thumbnailBlob' : [] | [ExternalBlob],
  'updatedAt' : Timestamp,
  'viewCount' : bigint,
  'durationSeconds' : bigint,
  'visibility' : VideoVisibility,
  'uploaderId' : UserId,
}
export type VideoId = bigint;
export type VideoStatus = { 'deleted' : null } |
  { 'available' : null };
export interface VideoSummary {
  'id' : VideoId,
  'status' : VideoStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'thumbnailBlob' : [] | [ExternalBlob],
  'viewCount' : bigint,
  'durationSeconds' : bigint,
  'visibility' : VideoVisibility,
  'uploaderId' : UserId,
}
export type VideoVisibility = { 'public' : null } |
  { 'private' : null } |
  { 'collaboratorsOnly' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptInvitation' : ActorMethod<[InvitationId], undefined>,
  'addComment' : ActorMethod<[CreateCommentInput], CommentId>,
  'addVideoToCollection' : ActorMethod<[CollectionId, VideoId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canEdit' : ActorMethod<[VideoId], boolean>,
  'createCollection' : ActorMethod<[CreateCollectionInput], CollectionId>,
  'declineInvitation' : ActorMethod<[InvitationId], undefined>,
  'deleteCollection' : ActorMethod<[CollectionId], undefined>,
  'deleteComment' : ActorMethod<[CommentId], undefined>,
  'deleteVideo' : ActorMethod<[VideoId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollaborator' : ActorMethod<[VideoId, UserId], [] | [Collaborator]>,
  'getCollection' : ActorMethod<[CollectionId], [] | [Collection]>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[VideoId], [] | [Video]>,
  'inviteCollaborator' : ActorMethod<
    [VideoId, UserId, CollaboratorRole],
    InvitationId
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCollaborators' : ActorMethod<[VideoId], Array<Collaborator>>,
  'listCollectionsByOwner' : ActorMethod<[UserId], Array<Collection>>,
  'listMyCollections' : ActorMethod<[], Array<Collection>>,
  'listMyVideos' : ActorMethod<[], Array<VideoSummary>>,
  'listPendingInvitations' : ActorMethod<[], Array<CollaborationInvitation>>,
  'listRecentVideos' : ActorMethod<[bigint], Array<VideoSummary>>,
  'listTrendingVideos' : ActorMethod<[bigint], Array<VideoSummary>>,
  'listVideoComments' : ActorMethod<[VideoId], Array<Comment>>,
  'listVideosByUser' : ActorMethod<[UserId], Array<VideoSummary>>,
  'register' : ActorMethod<[], undefined>,
  'removeVideoFromCollection' : ActorMethod<[CollectionId, VideoId], undefined>,
  'revokeCollaborator' : ActorMethod<[VideoId, UserId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[SaveProfileInput], undefined>,
  'searchVideos' : ActorMethod<[string], Array<VideoSummary>>,
  'updateCollection' : ActorMethod<
    [CollectionId, UpdateCollectionInput],
    undefined
  >,
  'updateProfile' : ActorMethod<[SaveProfileInput], undefined>,
  'updateVideo' : ActorMethod<[VideoId, UpdateVideoInput], undefined>,
  'uploadVideo' : ActorMethod<[CreateVideoInput], VideoId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];