/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const InvitationId = IDL.Nat;
export const VideoId = IDL.Nat;
export const CreateCommentInput = IDL.Record({
  'text' : IDL.Text,
  'timestampSeconds' : IDL.Nat,
  'videoId' : VideoId,
});
export const CommentId = IDL.Nat;
export const CollectionId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CollectionVisibility = IDL.Variant({
  'public' : IDL.Null,
  'private' : IDL.Null,
});
export const CreateCollectionInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'visibility' : CollectionVisibility,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const CollaboratorRole = IDL.Variant({
  'editor' : IDL.Null,
  'viewer' : IDL.Null,
});
export const Collaborator = IDL.Record({
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'role' : CollaboratorRole,
  'videoId' : VideoId,
});
export const Collection = IDL.Record({
  'id' : CollectionId,
  'title' : IDL.Text,
  'ownerId' : UserId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'visibility' : CollectionVisibility,
  'videoIds' : IDL.Vec(VideoId),
});
export const VideoStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'available' : IDL.Null,
});
export const VideoVisibility = IDL.Variant({
  'public' : IDL.Null,
  'private' : IDL.Null,
  'collaboratorsOnly' : IDL.Null,
});
export const Video = IDL.Record({
  'id' : VideoId,
  'status' : VideoStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'videoBlob' : ExternalBlob,
  'thumbnailBlob' : IDL.Opt(ExternalBlob),
  'updatedAt' : Timestamp,
  'viewCount' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'visibility' : VideoVisibility,
  'uploaderId' : UserId,
});
export const VideoSummary = IDL.Record({
  'id' : VideoId,
  'status' : VideoStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'thumbnailBlob' : IDL.Opt(ExternalBlob),
  'viewCount' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'visibility' : VideoVisibility,
  'uploaderId' : UserId,
});
export const InvitationStatus = IDL.Variant({
  'revoked' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const CollaborationInvitation = IDL.Record({
  'id' : InvitationId,
  'status' : InvitationStatus,
  'expiresAt' : Timestamp,
  'createdAt' : Timestamp,
  'role' : CollaboratorRole,
  'inviteeId' : UserId,
  'inviterId' : UserId,
  'videoId' : VideoId,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'timestampSeconds' : IDL.Nat,
  'videoId' : VideoId,
});
export const SaveProfileInput = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const UpdateCollectionInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'visibility' : CollectionVisibility,
});
export const UpdateVideoInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'visibility' : VideoVisibility,
});
export const CreateVideoInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'videoBlob' : ExternalBlob,
  'thumbnailBlob' : IDL.Opt(ExternalBlob),
  'durationSeconds' : IDL.Nat,
  'visibility' : VideoVisibility,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptInvitation' : IDL.Func([InvitationId], [], []),
  'addComment' : IDL.Func([CreateCommentInput], [CommentId], []),
  'addVideoToCollection' : IDL.Func([CollectionId, VideoId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canEdit' : IDL.Func([VideoId], [IDL.Bool], ['query']),
  'createCollection' : IDL.Func([CreateCollectionInput], [CollectionId], []),
  'declineInvitation' : IDL.Func([InvitationId], [], []),
  'deleteCollection' : IDL.Func([CollectionId], [], []),
  'deleteComment' : IDL.Func([CommentId], [], []),
  'deleteVideo' : IDL.Func([VideoId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollaborator' : IDL.Func(
      [VideoId, UserId],
      [IDL.Opt(Collaborator)],
      ['query'],
    ),
  'getCollection' : IDL.Func([CollectionId], [IDL.Opt(Collection)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], []),
  'inviteCollaborator' : IDL.Func(
      [VideoId, UserId, CollaboratorRole],
      [InvitationId],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCollaborators' : IDL.Func([VideoId], [IDL.Vec(Collaborator)], ['query']),
  'listCollectionsByOwner' : IDL.Func(
      [UserId],
      [IDL.Vec(Collection)],
      ['query'],
    ),
  'listMyCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
  'listMyVideos' : IDL.Func([], [IDL.Vec(VideoSummary)], ['query']),
  'listPendingInvitations' : IDL.Func(
      [],
      [IDL.Vec(CollaborationInvitation)],
      ['query'],
    ),
  'listRecentVideos' : IDL.Func([IDL.Nat], [IDL.Vec(VideoSummary)], ['query']),
  'listTrendingVideos' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(VideoSummary)],
      ['query'],
    ),
  'listVideoComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
  'listVideosByUser' : IDL.Func([UserId], [IDL.Vec(VideoSummary)], ['query']),
  'register' : IDL.Func([], [], []),
  'removeVideoFromCollection' : IDL.Func([CollectionId, VideoId], [], []),
  'revokeCollaborator' : IDL.Func([VideoId, UserId], [], []),
  'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoSummary)], ['query']),
  'updateCollection' : IDL.Func([CollectionId, UpdateCollectionInput], [], []),
  'updateProfile' : IDL.Func([SaveProfileInput], [], []),
  'updateVideo' : IDL.Func([VideoId, UpdateVideoInput], [], []),
  'uploadVideo' : IDL.Func([CreateVideoInput], [VideoId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const InvitationId = IDL.Nat;
  const VideoId = IDL.Nat;
  const CreateCommentInput = IDL.Record({
    'text' : IDL.Text,
    'timestampSeconds' : IDL.Nat,
    'videoId' : VideoId,
  });
  const CommentId = IDL.Nat;
  const CollectionId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CollectionVisibility = IDL.Variant({
    'public' : IDL.Null,
    'private' : IDL.Null,
  });
  const CreateCollectionInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'visibility' : CollectionVisibility,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const CollaboratorRole = IDL.Variant({
    'editor' : IDL.Null,
    'viewer' : IDL.Null,
  });
  const Collaborator = IDL.Record({
    'userId' : UserId,
    'joinedAt' : Timestamp,
    'role' : CollaboratorRole,
    'videoId' : VideoId,
  });
  const Collection = IDL.Record({
    'id' : CollectionId,
    'title' : IDL.Text,
    'ownerId' : UserId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'visibility' : CollectionVisibility,
    'videoIds' : IDL.Vec(VideoId),
  });
  const VideoStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'available' : IDL.Null,
  });
  const VideoVisibility = IDL.Variant({
    'public' : IDL.Null,
    'private' : IDL.Null,
    'collaboratorsOnly' : IDL.Null,
  });
  const Video = IDL.Record({
    'id' : VideoId,
    'status' : VideoStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'videoBlob' : ExternalBlob,
    'thumbnailBlob' : IDL.Opt(ExternalBlob),
    'updatedAt' : Timestamp,
    'viewCount' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'visibility' : VideoVisibility,
    'uploaderId' : UserId,
  });
  const VideoSummary = IDL.Record({
    'id' : VideoId,
    'status' : VideoStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'thumbnailBlob' : IDL.Opt(ExternalBlob),
    'viewCount' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'visibility' : VideoVisibility,
    'uploaderId' : UserId,
  });
  const InvitationStatus = IDL.Variant({
    'revoked' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const CollaborationInvitation = IDL.Record({
    'id' : InvitationId,
    'status' : InvitationStatus,
    'expiresAt' : Timestamp,
    'createdAt' : Timestamp,
    'role' : CollaboratorRole,
    'inviteeId' : UserId,
    'inviterId' : UserId,
    'videoId' : VideoId,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'timestampSeconds' : IDL.Nat,
    'videoId' : VideoId,
  });
  const SaveProfileInput = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const UpdateCollectionInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'visibility' : CollectionVisibility,
  });
  const UpdateVideoInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'visibility' : VideoVisibility,
  });
  const CreateVideoInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'videoBlob' : ExternalBlob,
    'thumbnailBlob' : IDL.Opt(ExternalBlob),
    'durationSeconds' : IDL.Nat,
    'visibility' : VideoVisibility,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptInvitation' : IDL.Func([InvitationId], [], []),
    'addComment' : IDL.Func([CreateCommentInput], [CommentId], []),
    'addVideoToCollection' : IDL.Func([CollectionId, VideoId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canEdit' : IDL.Func([VideoId], [IDL.Bool], ['query']),
    'createCollection' : IDL.Func([CreateCollectionInput], [CollectionId], []),
    'declineInvitation' : IDL.Func([InvitationId], [], []),
    'deleteCollection' : IDL.Func([CollectionId], [], []),
    'deleteComment' : IDL.Func([CommentId], [], []),
    'deleteVideo' : IDL.Func([VideoId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollaborator' : IDL.Func(
        [VideoId, UserId],
        [IDL.Opt(Collaborator)],
        ['query'],
      ),
    'getCollection' : IDL.Func(
        [CollectionId],
        [IDL.Opt(Collection)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], []),
    'inviteCollaborator' : IDL.Func(
        [VideoId, UserId, CollaboratorRole],
        [InvitationId],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCollaborators' : IDL.Func(
        [VideoId],
        [IDL.Vec(Collaborator)],
        ['query'],
      ),
    'listCollectionsByOwner' : IDL.Func(
        [UserId],
        [IDL.Vec(Collection)],
        ['query'],
      ),
    'listMyCollections' : IDL.Func([], [IDL.Vec(Collection)], ['query']),
    'listMyVideos' : IDL.Func([], [IDL.Vec(VideoSummary)], ['query']),
    'listPendingInvitations' : IDL.Func(
        [],
        [IDL.Vec(CollaborationInvitation)],
        ['query'],
      ),
    'listRecentVideos' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(VideoSummary)],
        ['query'],
      ),
    'listTrendingVideos' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(VideoSummary)],
        ['query'],
      ),
    'listVideoComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
    'listVideosByUser' : IDL.Func([UserId], [IDL.Vec(VideoSummary)], ['query']),
    'register' : IDL.Func([], [], []),
    'removeVideoFromCollection' : IDL.Func([CollectionId, VideoId], [], []),
    'revokeCollaborator' : IDL.Func([VideoId, UserId], [], []),
    'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoSummary)], ['query']),
    'updateCollection' : IDL.Func(
        [CollectionId, UpdateCollectionInput],
        [],
        [],
      ),
    'updateProfile' : IDL.Func([SaveProfileInput], [], []),
    'updateVideo' : IDL.Func([VideoId, UpdateVideoInput], [], []),
    'uploadVideo' : IDL.Func([CreateVideoInput], [VideoId], []),
  });
};

export const init = ({ IDL }) => { return []; };