/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: VideoId;
    status: VideoStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    videoBlob: ExternalBlob;
    thumbnailBlob?: ExternalBlob;
    updatedAt: Timestamp;
    viewCount: bigint;
    durationSeconds: bigint;
    visibility: VideoVisibility;
    uploaderId: UserId;
}
export type Timestamp = bigint;
export interface CreateCommentInput {
    text: string;
    timestampSeconds: bigint;
    videoId: VideoId;
}
export interface VideoSummary {
    id: VideoId;
    status: VideoStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    thumbnailBlob?: ExternalBlob;
    viewCount: bigint;
    durationSeconds: bigint;
    visibility: VideoVisibility;
    uploaderId: UserId;
}
export interface UpdateCollectionInput {
    title: string;
    description: string;
    visibility: CollectionVisibility;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface CreateVideoInput {
    title: string;
    description: string;
    videoBlob: ExternalBlob;
    thumbnailBlob?: ExternalBlob;
    durationSeconds: bigint;
    visibility: VideoVisibility;
}
export interface CollaborationInvitation {
    id: InvitationId;
    status: InvitationStatus;
    expiresAt: Timestamp;
    createdAt: Timestamp;
    role: CollaboratorRole;
    inviteeId: UserId;
    inviterId: UserId;
    videoId: VideoId;
}
export interface UpdateVideoInput {
    title: string;
    description: string;
    visibility: VideoVisibility;
}
export interface Collaborator {
    userId: UserId;
    joinedAt: Timestamp;
    role: CollaboratorRole;
    videoId: VideoId;
}
export type VideoId = bigint;
export type CollectionId = bigint;
export interface SaveProfileInput {
    bio: string;
    displayName: string;
    profilePicture?: ExternalBlob;
}
export interface CreateCollectionInput {
    title: string;
    description: string;
    visibility: CollectionVisibility;
}
export type CommentId = bigint;
export interface Comment {
    id: CommentId;
    authorId: UserId;
    createdAt: Timestamp;
    text: string;
    timestampSeconds: bigint;
    videoId: VideoId;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type UserId = Principal;
export interface Collection {
    id: CollectionId;
    title: string;
    ownerId: UserId;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    visibility: CollectionVisibility;
    videoIds: Array<VideoId>;
}
export interface UserProfile {
    id: UserId;
    bio: string;
    displayName: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    profilePicture?: ExternalBlob;
}
export type InvitationId = bigint;
export enum CollaboratorRole {
    editor = "editor",
    viewer = "viewer"
}
export enum CollectionVisibility {
    public_ = "public",
    private_ = "private"
}
export enum InvitationStatus {
    revoked = "revoked",
    expired = "expired",
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VideoStatus {
    deleted = "deleted",
    available = "available"
}
export enum VideoVisibility {
    public_ = "public",
    private_ = "private",
    collaboratorsOnly = "collaboratorsOnly"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptInvitation(invitationId: InvitationId): Promise<void>;
    addComment(input: CreateCommentInput): Promise<CommentId>;
    addVideoToCollection(collectionId: CollectionId, videoId: VideoId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    canEdit(videoId: VideoId): Promise<boolean>;
    createCollection(input: CreateCollectionInput): Promise<CollectionId>;
    declineInvitation(invitationId: InvitationId): Promise<void>;
    deleteCollection(id: CollectionId): Promise<void>;
    deleteComment(commentId: CommentId): Promise<void>;
    deleteVideo(id: VideoId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCollaborator(videoId: VideoId, userId: UserId): Promise<Collaborator | null>;
    getCollection(id: CollectionId): Promise<Collection | null>;
    getProfile(): Promise<UserProfile | null>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    getVideo(id: VideoId): Promise<Video | null>;
    inviteCollaborator(videoId: VideoId, inviteeId: UserId, role: CollaboratorRole): Promise<InvitationId>;
    isCallerAdmin(): Promise<boolean>;
    listCollaborators(videoId: VideoId): Promise<Array<Collaborator>>;
    listCollectionsByOwner(ownerId: UserId): Promise<Array<Collection>>;
    listMyCollections(): Promise<Array<Collection>>;
    listMyVideos(): Promise<Array<VideoSummary>>;
    listPendingInvitations(): Promise<Array<CollaborationInvitation>>;
    listRecentVideos(limit: bigint): Promise<Array<VideoSummary>>;
    listTrendingVideos(limit: bigint): Promise<Array<VideoSummary>>;
    listVideoComments(videoId: VideoId): Promise<Array<Comment>>;
    listVideosByUser(uploaderId: UserId): Promise<Array<VideoSummary>>;
    register(): Promise<void>;
    removeVideoFromCollection(collectionId: CollectionId, videoId: VideoId): Promise<void>;
    revokeCollaborator(videoId: VideoId, targetUserId: UserId): Promise<void>;
    saveCallerUserProfile(input: SaveProfileInput): Promise<void>;
    searchVideos(searchTerm: string): Promise<Array<VideoSummary>>;
    updateCollection(id: CollectionId, input: UpdateCollectionInput): Promise<void>;
    updateProfile(input: SaveProfileInput): Promise<void>;
    updateVideo(id: VideoId, input: UpdateVideoInput): Promise<void>;
    uploadVideo(input: CreateVideoInput): Promise<VideoId>;
}
import type { CollaborationInvitation as _CollaborationInvitation, Collaborator as _Collaborator, CollaboratorRole as _CollaboratorRole, Collection as _Collection, CollectionId as _CollectionId, CollectionVisibility as _CollectionVisibility, CreateCollectionInput as _CreateCollectionInput, CreateVideoInput as _CreateVideoInput, ExternalBlob as _ExternalBlob, InvitationId as _InvitationId, InvitationStatus as _InvitationStatus, SaveProfileInput as _SaveProfileInput, Timestamp as _Timestamp, UpdateCollectionInput as _UpdateCollectionInput, UpdateVideoInput as _UpdateVideoInput, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, Video as _Video, VideoId as _VideoId, VideoStatus as _VideoStatus, VideoSummary as _VideoSummary, VideoVisibility as _VideoVisibility, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptInvitation(arg0: InvitationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptInvitation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptInvitation(arg0);
            return result;
        }
    }
    async addComment(arg0: CreateCommentInput): Promise<CommentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0);
            return result;
        }
    }
    async addVideoToCollection(arg0: CollectionId, arg1: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideoToCollection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideoToCollection(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async canEdit(arg0: VideoId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canEdit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canEdit(arg0);
            return result;
        }
    }
    async createCollection(arg0: CreateCollectionInput): Promise<CollectionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollection(to_candid_CreateCollectionInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollection(to_candid_CreateCollectionInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async declineInvitation(arg0: InvitationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineInvitation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineInvitation(arg0);
            return result;
        }
    }
    async deleteCollection(arg0: CollectionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollection(arg0);
            return result;
        }
    }
    async deleteComment(arg0: CommentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollaborator(arg0: VideoId, arg1: UserId): Promise<Collaborator | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollaborator(arg0, arg1);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollaborator(arg0, arg1);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollection(arg0: CollectionId): Promise<Collection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollection(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollection(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideo(arg0: VideoId): Promise<Video | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async inviteCollaborator(arg0: VideoId, arg1: UserId, arg2: CollaboratorRole): Promise<InvitationId> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteCollaborator(arg0, arg1, to_candid_CollaboratorRole_n38(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteCollaborator(arg0, arg1, to_candid_CollaboratorRole_n38(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCollaborators(arg0: VideoId): Promise<Array<Collaborator>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCollaborators(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCollaborators(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCollectionsByOwner(arg0: UserId): Promise<Array<Collection>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCollectionsByOwner(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCollectionsByOwner(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyCollections(): Promise<Array<Collection>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyCollections();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyCollections();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyVideos(): Promise<Array<VideoSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyVideos();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyVideos();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingInvitations(): Promise<Array<CollaborationInvitation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingInvitations();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingInvitations();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRecentVideos(arg0: bigint): Promise<Array<VideoSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecentVideos(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecentVideos(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTrendingVideos(arg0: bigint): Promise<Array<VideoSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrendingVideos(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrendingVideos(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVideoComments(arg0: VideoId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVideoComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVideoComments(arg0);
            return result;
        }
    }
    async listVideosByUser(arg0: UserId): Promise<Array<VideoSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVideosByUser(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVideosByUser(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register();
            return result;
        }
    }
    async removeVideoFromCollection(arg0: CollectionId, arg1: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeVideoFromCollection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeVideoFromCollection(arg0, arg1);
            return result;
        }
    }
    async revokeCollaborator(arg0: VideoId, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeCollaborator(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeCollaborator(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: SaveProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_SaveProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_SaveProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchVideos(arg0: string): Promise<Array<VideoSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVideos(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVideos(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCollection(arg0: CollectionId, arg1: UpdateCollectionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollection(arg0, to_candid_UpdateCollectionInput_n53(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollection(arg0, to_candid_UpdateCollectionInput_n53(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProfile(arg0: SaveProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(await to_candid_SaveProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(await to_candid_SaveProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateVideo(arg0: VideoId, arg1: UpdateVideoInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideo(arg0, to_candid_UpdateVideoInput_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideo(arg0, to_candid_UpdateVideoInput_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadVideo(arg0: CreateVideoInput): Promise<VideoId> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideo(await to_candid_CreateVideoInput_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideo(await to_candid_CreateVideoInput_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CollaborationInvitation_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollaborationInvitation): CollaborationInvitation {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_CollaboratorRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollaboratorRole): CollaboratorRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Collaborator_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Collaborator): Collaborator {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_CollectionVisibility_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectionVisibility): CollectionVisibility {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Collection_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Collection): Collection {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InvitationStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvitationStatus): InvitationStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_VideoStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoStatus): VideoStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoSummary_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoSummary): Promise<VideoSummary> {
    return await from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_VideoVisibility_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoVisibility): VideoVisibility {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Collaborator]): Collaborator | null {
    return value.length === 0 ? null : from_candid_Collaborator_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Collection]): Collection | null {
    return value.length === 0 ? null : from_candid_Collection_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Video]): Promise<Video | null> {
    return value.length === 0 ? null : await from_candid_Video_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    displayName: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    profilePicture: [] | [_ExternalBlob];
}): Promise<{
    id: UserId;
    bio: string;
    displayName: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    profilePicture?: ExternalBlob;
}> {
    return {
        id: value.id,
        bio: value.bio,
        displayName: value.displayName,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n17(_uploadFile, _downloadFile, value.profilePicture))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    joinedAt: _Timestamp;
    role: _CollaboratorRole;
    videoId: _VideoId;
}): {
    userId: UserId;
    joinedAt: Timestamp;
    role: CollaboratorRole;
    videoId: VideoId;
} {
    return {
        userId: value.userId,
        joinedAt: value.joinedAt,
        role: from_candid_CollaboratorRole_n24(_uploadFile, _downloadFile, value.role),
        videoId: value.videoId
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CollectionId;
    title: string;
    ownerId: _UserId;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    visibility: _CollectionVisibility;
    videoIds: Array<_VideoId>;
}): {
    id: CollectionId;
    title: string;
    ownerId: UserId;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    visibility: CollectionVisibility;
    videoIds: Array<VideoId>;
} {
    return {
        id: value.id,
        title: value.title,
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        visibility: from_candid_CollectionVisibility_n29(_uploadFile, _downloadFile, value.visibility),
        videoIds: value.videoIds
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    status: _VideoStatus;
    title: string;
    createdAt: _Timestamp;
    description: string;
    videoBlob: _ExternalBlob;
    thumbnailBlob: [] | [_ExternalBlob];
    updatedAt: _Timestamp;
    viewCount: bigint;
    durationSeconds: bigint;
    visibility: _VideoVisibility;
    uploaderId: _UserId;
}): Promise<{
    id: VideoId;
    status: VideoStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    videoBlob: ExternalBlob;
    thumbnailBlob?: ExternalBlob;
    updatedAt: Timestamp;
    viewCount: bigint;
    durationSeconds: bigint;
    visibility: VideoVisibility;
    uploaderId: UserId;
}> {
    return {
        id: value.id,
        status: from_candid_VideoStatus_n34(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        videoBlob: await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.videoBlob),
        thumbnailBlob: record_opt_to_undefined(await from_candid_opt_n17(_uploadFile, _downloadFile, value.thumbnailBlob)),
        updatedAt: value.updatedAt,
        viewCount: value.viewCount,
        durationSeconds: value.durationSeconds,
        visibility: from_candid_VideoVisibility_n36(_uploadFile, _downloadFile, value.visibility),
        uploaderId: value.uploaderId
    };
}
async function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    status: _VideoStatus;
    title: string;
    createdAt: _Timestamp;
    description: string;
    thumbnailBlob: [] | [_ExternalBlob];
    viewCount: bigint;
    durationSeconds: bigint;
    visibility: _VideoVisibility;
    uploaderId: _UserId;
}): Promise<{
    id: VideoId;
    status: VideoStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    thumbnailBlob?: ExternalBlob;
    viewCount: bigint;
    durationSeconds: bigint;
    visibility: VideoVisibility;
    uploaderId: UserId;
}> {
    return {
        id: value.id,
        status: from_candid_VideoStatus_n34(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        thumbnailBlob: record_opt_to_undefined(await from_candid_opt_n17(_uploadFile, _downloadFile, value.thumbnailBlob)),
        viewCount: value.viewCount,
        durationSeconds: value.durationSeconds,
        visibility: from_candid_VideoVisibility_n36(_uploadFile, _downloadFile, value.visibility),
        uploaderId: value.uploaderId
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InvitationId;
    status: _InvitationStatus;
    expiresAt: _Timestamp;
    createdAt: _Timestamp;
    role: _CollaboratorRole;
    inviteeId: _UserId;
    inviterId: _UserId;
    videoId: _VideoId;
}): {
    id: InvitationId;
    status: InvitationStatus;
    expiresAt: Timestamp;
    createdAt: Timestamp;
    role: CollaboratorRole;
    inviteeId: UserId;
    inviterId: UserId;
    videoId: VideoId;
} {
    return {
        id: value.id,
        status: from_candid_InvitationStatus_n48(_uploadFile, _downloadFile, value.status),
        expiresAt: value.expiresAt,
        createdAt: value.createdAt,
        role: from_candid_CollaboratorRole_n24(_uploadFile, _downloadFile, value.role),
        inviteeId: value.inviteeId,
        inviterId: value.inviterId,
        videoId: value.videoId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    editor: null;
} | {
    viewer: null;
}): CollaboratorRole {
    return "editor" in value ? CollaboratorRole.editor : "viewer" in value ? CollaboratorRole.viewer : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    public: null;
} | {
    private: null;
}): CollectionVisibility {
    return "public" in value ? CollectionVisibility.public : "private" in value ? CollectionVisibility.private : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deleted: null;
} | {
    available: null;
}): VideoStatus {
    return "deleted" in value ? VideoStatus.deleted : "available" in value ? VideoStatus.available : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    public: null;
} | {
    private: null;
} | {
    collaboratorsOnly: null;
}): VideoVisibility {
    return "public" in value ? VideoVisibility.public : "private" in value ? VideoVisibility.private : "collaboratorsOnly" in value ? VideoVisibility.collaboratorsOnly : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    revoked: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): InvitationStatus {
    return "revoked" in value ? InvitationStatus.revoked : "expired" in value ? InvitationStatus.expired : "pending" in value ? InvitationStatus.pending : "accepted" in value ? InvitationStatus.accepted : "declined" in value ? InvitationStatus.declined : value;
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Collaborator>): Array<Collaborator> {
    return value.map((x)=>from_candid_Collaborator_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Collection>): Array<Collection> {
    return value.map((x)=>from_candid_Collection_n27(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoSummary>): Promise<Array<VideoSummary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoSummary_n43(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CollaborationInvitation>): Array<CollaborationInvitation> {
    return value.map((x)=>from_candid_CollaborationInvitation_n46(_uploadFile, _downloadFile, x));
}
function to_candid_CollaboratorRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollaboratorRole): _CollaboratorRole {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_CollectionVisibility_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollectionVisibility): _CollectionVisibility {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_CreateCollectionInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateCollectionInput): _CreateCollectionInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateVideoInput_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateVideoInput): Promise<_CreateVideoInput> {
    return await to_candid_record_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_SaveProfileInput_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveProfileInput): Promise<_SaveProfileInput> {
    return await to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateCollectionInput_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateCollectionInput): _UpdateCollectionInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateVideoInput_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateVideoInput): _UpdateVideoInput {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VideoVisibility_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoVisibility): _VideoVisibility {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    visibility: CollectionVisibility;
}): {
    title: string;
    description: string;
    visibility: _CollectionVisibility;
} {
    return {
        title: value.title,
        description: value.description,
        visibility: to_candid_CollectionVisibility_n12(_uploadFile, _downloadFile, value.visibility)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    profilePicture?: ExternalBlob;
}): Promise<{
    bio: string;
    displayName: string;
    profilePicture: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        displayName: value.displayName,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n52(_uploadFile, _downloadFile, value.profilePicture)) : candid_none()
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    visibility: VideoVisibility;
}): {
    title: string;
    description: string;
    visibility: _VideoVisibility;
} {
    return {
        title: value.title,
        description: value.description,
        visibility: to_candid_VideoVisibility_n56(_uploadFile, _downloadFile, value.visibility)
    };
}
async function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    videoBlob: ExternalBlob;
    thumbnailBlob?: ExternalBlob;
    durationSeconds: bigint;
    visibility: VideoVisibility;
}): Promise<{
    title: string;
    description: string;
    videoBlob: _ExternalBlob;
    thumbnailBlob: [] | [_ExternalBlob];
    durationSeconds: bigint;
    visibility: _VideoVisibility;
}> {
    return {
        title: value.title,
        description: value.description,
        videoBlob: await to_candid_ExternalBlob_n52(_uploadFile, _downloadFile, value.videoBlob),
        thumbnailBlob: value.thumbnailBlob ? candid_some(await to_candid_ExternalBlob_n52(_uploadFile, _downloadFile, value.thumbnailBlob)) : candid_none(),
        durationSeconds: value.durationSeconds,
        visibility: to_candid_VideoVisibility_n56(_uploadFile, _downloadFile, value.visibility)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollectionVisibility): {
    public: null;
} | {
    private: null;
} {
    return value == CollectionVisibility.public ? {
        public_: null
    } : value == CollectionVisibility.private ? {
        private_: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollaboratorRole): {
    editor: null;
} | {
    viewer: null;
} {
    return value == CollaboratorRole.editor ? {
        editor: null
    } : value == CollaboratorRole.viewer ? {
        viewer: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoVisibility): {
    public: null;
} | {
    private: null;
} | {
    collaboratorsOnly: null;
} {
    return value == VideoVisibility.public ? {
        public_: null
    } : value == VideoVisibility.private ? {
        private_: null
    } : value == VideoVisibility.collaboratorsOnly ? {
        collaboratorsOnly: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
